### ISSUE TITLE
Failed to install addon, Unknown Error, see logs

### ISSUE THREAD

**Issue by luisfosoares** [davidramosweb/hassio-addons#10] opened 2020-02-27 10:23 UTC
Hello, 

I cannot install it on my Home assistant 

I have latest version fully updated but when i try to install i get ´

`"Failed to install addon, Unknown Error, see logs"`

No logs are provided unfortunately

**Comment by JediDork** [comment] 2020-03-07 07:58
Same issue, latest version of HASS.IO and trying to install v1.0.2 of Hassio Hostapd. No logs.

**Comment by shshemi** [comment] 2020-04-14 11:13
Same here

**Comment by LewisW-J** [comment] 2020-04-15 17:21
Getting the same error, looking at sytem log:

ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build 567c2022/armv7-addon-hassio-hostapd:1.0.2: The command '/bin/bash -o pipefail -c apk update && apk add --no-cache bash jq iw hostapd networkmanager=1.18.1-r2 net-tools=1.60_git20140218-r2 sudo=1.8.27-r0 && rm -rf /var/cache/apk/*' returned a non-zero code: 2

**Comment by davidramosweb** [comment] 2020-04-22 15:12
Duplicate of #7

**Closed as completed by davidramosweb** 2020-04-22 15:12 UTC
